# argocd/application-n8n-saas.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-saas-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcksdbgg/m8-manifest'
    path: . # Directorio raíz del repositorio
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    # El namespace es irrelevante aquí, ya que cada recurso tiene el suyo.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true