apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-tenant-b-ingress
  namespace: n8n-tenants
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "tenant-b.n8n.tu-dominio.com" # <-- REEMPLAZA
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-tenant-b-svc
            port:
              number: 5678