apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatwoot-tenant-a-ingress
  namespace: n8n-tenants
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Si usas Cert-Manager, descomenta la l√≠nea siguiente
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: "chat-tenant-a.n8n.atenex.pe"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatwoot-tenant-a-svc
            port:
              number: 3000
  tls:
  - hosts:
    - chat-tenant-a.n8n.atenex.pe
    # Reutilizamos el secreto TLS si es wildcard, o creamos uno nuevo
    secretName: chatwoot-tenant-a-tls-secret